#!/usr/bin/env python

import os
import os.path
import subprocess
import sys

DIR = os.path.abspath(os.path.dirname(sys.argv[0]))


def _compile_markdown(top_level_path, path):
  uri_parts = os.path.splitext(path)[0].split('/')
  while uri_parts[-1] == 'index':
    uri_parts.pop()
  uri = '/'.join(uri_parts)[len(top_level_path):]

  print '%s -> html/compiled%s.htm' % (path[len(top_level_path):], uri)
  html = subprocess.check_output([DIR + '/components/output_markdown.php',
                                  path, uri])

  output = '%s/html/compiled%s.htm' % (os.path.dirname(top_level_path), uri)
  if not os.path.isdir(os.path.dirname(output)):
    os.makedirs(os.path.dirname(output))
  with file(output, 'w') as fd:
    fd.write(html)


def compile_markdown(path):

  def visit(arg, dirname, names):
    for name in names:
      if name.endswith('.txt'):
        _compile_markdown(path, '%s/%s' % (dirname, name))

  os.path.walk(path, visit, None)

if __name__ == '__main__':
  compile_markdown(DIR + '/pages')
