#!/usr/bin/php
<?php
require 'init.php';

Config::write('server', 'mode', 'development');
$_SERVER['SERVER_NAME'] = 'localhost';

function compile($path) {
  foreach (glob("$path/*") as $filename) {
    if (ends_with($filename, '.txt')) {
      // @hack: to be replaced with python
      $uri = substr($filename, 7, -4);
      while (ends_with($uri, '/index')) {
        $uri = substr($uri, 0, -6);
      }
      $_SERVER['REQUEST_URI'] = $uri;

      $output = "./html/compiled$uri.htm";
      system('mkdir -p '.dirname($output));

      print "$filename > $output\n";
      $view = new View_Markdown($filename, array());
      Layout_Page::reset();
      ob_start();
      Layout_Page::header();
      $view->render();
      Layout_Page::footer();
      file_put_contents($output, ob_get_clean());

    }elseif (is_dir($filename)) {
      compile($filename);
    }
  }
}

compile('./pages');
