#!/usr/bin/env python

import os.path
import re


def update_chunk(matchobj):
  curl_cmd = []
  for line in matchobj.group(1).splitlines():
    line = line.strip()
    if not line:
      continue

    assert line[0] in '$>'
    line = line[1:]

    if line.endswith('\\'):
      line = line[:-2]

    curl_cmd.append(line.strip())
  curl_cmd = ' '.join(curl_cmd)

  # TODO replace bits of the cmd with new parameters and run the request
  print curl_cmd
  print


def update_curl_example(path):
  with file(path) as fd:
    content = fd.read()

  regex = r'<div class="input">(.*?)</div>\w*(<div class="output">.*?</div>)?'
  new_content = re.sub(regex, update_chunk, content, flags=re.DOTALL)

  if content != new_content:
    # TODO update content
    pass


def main(path):

  def visit(arg, dirname, names):
    for name in names:
      if name.endswith('.txt'):
        update_curl_example('%s/%s' % (dirname, name))

  os.path.walk(path, visit, None)


if __name__ == '__main__':
  import sys
  main(os.path.abspath(os.path.dirname(sys.argv[0])) + '/pages')
